# Generated by Django 4.2.11 on 2025-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='offline_file',
            field=models.FileField(blank=True, help_text='Upload ZIP file containing the complete website (only for offline portfolios)', null=True, upload_to='portfolio/offline/', verbose_name='Offline File'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='portfolio_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10, verbose_name='Portfolio Type'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='url',
            field=models.URLField(blank=True, help_text='Website URL (only for online portfolios)', null=True, verbose_name='URL'),
        ),
    ]
