# Generated by Django 5.2.8 on 2025-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_offline_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='language',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='service',
            name='language',
        ),
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hero',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hero',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hero',
            name='subtitle_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='hero',
            name='subtitle_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
