# Generated by Django 4.2.11 on 2025-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_about_content_alter_about_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Site Title')),
                ('site_title_en', models.CharField(max_length=200, null=True, verbose_name='Site Title')),
                ('site_title_fa', models.CharField(max_length=200, null=True, verbose_name='Site Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
