# Generated by Django 4.2.11 on 2025-11-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=120, null=True, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Role')),
                ('role_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Role')),
                ('role_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Role')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_fa', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
