# Generated by Django 4.2.11 on 2025-11-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_teamsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram URL'),
        ),
    ]
