# Generated by Django 4.2.11 on 2025-11-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_contactinfo_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
    ]
