# Generated by Django 4.2.11 on 2025-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_contactinfo_instagram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.technology', verbose_name='Technologies'),
        ),
    ]
