# Generated by Django 4.2.11 on 2025-11-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_technology_portfolioitem_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_fa',
        ),
    ]
